version: '3.8'

services:
  test:
    build: .
    command: python -m pytest src/api/api_tests.py -v --tb=short
    volumes:
      - ./src:/app/src
      - ./database:/app/database
      - ./datasets:/app/datasets
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    profiles: ["test"]
    # Exit after tests complete
    restart: "no"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./database:/app/database
      - ./datasets:/app/datasets
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Only depend on test when test profile is enabled
    depends_on: {}
